### ISSUE TITLE
Glyph metrics?

### ISSUE THREAD

**Issue by pkgw** [dfrg/pinot#2]
Hi,

I'm interested in using Pinot in [Tectonic](https://tectonic-typesetting.github.io/) for generating high-quality HTML from TeX. It's worked well so far for my first task, which is reverse-engineering which Unicode inputs generate which glyphs.

For my next problem, I'd like to get the metrics associated with specific glyphs. Am I correct that Pinot doesn't currently support that? Is this feature something that might appear in Pinot soon, by any chance?

**Comment by pkgw** [comment]
When I filed this I recall that I had checked Pinot for some of the APIs I needed and wasn't seeing them, but now that I'm looking at things again I think it's got everything I need. I'll close this until/unless I can come up with a more specific request.

**Comment by dfrg** [comment]
No worries. I’m mostly moving internal code over from swash as I find the time. If you do have any needs for specific tables just let me know and I’ll prioritize those.
